# Generated by Django 2.2.5 on 2021-12-22 14:07

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarPath',
            field=models.ImageField(blank=True, default='upload/userAvatar/default.png', max_length=300, null=True, upload_to=apps.users.models.user_directory_path, verbose_name='头像'),
        ),
    ]
