# Generated by Django 2.2.5 on 2021-12-24 12:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatarpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarPath',
            field=models.ImageField(default='upload/userAvatar/default.png', max_length=300, upload_to=apps.users.models.user_directory_path, verbose_name='头像'),
        ),
    ]
