# Generated by Django 2.2.5 on 2021-12-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='创建时间')),
                ('modifiedDate', models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='最近修改时间')),
                ('description', models.TextField(blank=True, verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'blog_articles',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章标签管理',
                'verbose_name_plural': '文章标签管理',
                'db_table': 'blog_tags',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(default='学习日志', max_length=20, primary_key=True, serialize=False, verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章类型管理',
                'verbose_name_plural': '文章类型管理',
                'db_table': 'blog_types',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Article')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Tag')),
            ],
            options={
                'verbose_name': '文章标签关系管理',
                'verbose_name_plural': '文章标签关系管理',
                'db_table': 'blog_articles_tag_relations',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, through='articles.ArticleTag', to='articles.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default='学习日志', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='type_art', to='articles.Type', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_art', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
