# Generated by Django 2.2.5 on 2021-12-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211231_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bgImgPath',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='文章首页背景图'),
        ),
    ]
