# Generated by Django 2.2.5 on 2021-12-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_bgimgpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
