# Generated by Django 2.2.5 on 2021-12-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='value',
            field=models.CharField(default='学习日志', max_length=20, verbose_name='分类值'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='learnlog', max_length=20, primary_key=True, serialize=False, verbose_name='分类'),
        ),
    ]
