# Generated by Django 2.2.5 on 2021-12-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211231_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='value',
        ),
    ]
