# Generated by Django 2.2.5 on 2021-12-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_type_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_art', through='articles.ArticleTag', to='articles.Tag', verbose_name='标签'),
        ),
    ]
