# Generated by Django 2.2.5 on 2022-01-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20220101_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.CharField(blank=True, choices=[('byself', 'byself'), ('byother', 'byother')], max_length=20, verbose_name='状态'),
        ),
    ]
