# Generated by Django 2.2.5 on 2022-01-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20220101_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='digest',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
    ]
